version: '2.2'
services:
  elasticsearch:
    build:
      context: elasticsearch/
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - transport.tcp.port=9300  
      - transport.publish_host=localhost
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    depends_on: 
    - elasticsearch
    build:
      context: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - 5601:5601
    environment: 
      - SERVER_HOST=0.0.0.0
  grafana:
    build:
      context: grafana/
    ports:
      - 3000:3000
    volumes:
      - ./grafana/config:/var/lib/grafana
    user: "104"

  # logstash:
  #   build:
  #     context: logstash/
  #   volumes:
  #     - ./logstash/config/:/usr/share/logstash/pipeline
  #   networks:
  #     - esnet
volumes:
  esdata1:
    driver: local